## 端口号
server:
  port: 8080
## 项目名称
spring:
  application:
    name: lgl-service-consumer
## eureka配置
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka,http://127.0.0.1:10087/eureka,http://127.0.0.1:10088/eureka
    register-with-eureka: true # 服务提供方,会检测该参数是否为true,true-注册给eureka(是否注册到eureka服务中心,默认为true)
    fetch-registry: true #消费方 是否开启检索服务
    registry-fetch-interval-seconds: 5 #消费方 更新本地服务器列表缓存的间隔时间
  instance:
    lease-expiration-duration-in-seconds: 15 #过期间隔时间,默认为90s
    lease-renewal-interval-in-seconds: 5 #心跳间隔时间,默认为30s
## ribbon负载均衡配置
lgl-service-provider: # 服务提供方的服务id
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.BestAvailableRule # 负载均衡策略:com.netflix.loadbalancer.RandomRule 随机负载
## hystrix相关配置
hystrix:
  command:
    default:
     execution:
       isolation:
         thread:
           timeoutInMilliseconds: 6000 # 设置hystrix的超时时间为6000ms
## 开启Feign的熔断功能
feign:
  hystrix:
    enabled: true
