## 端口号
server:
  port: 10086
## 服务名称
spring:
  application:
    name: leyou-registry
## eureka注册中心
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
    register-with-eureka: false # 是否在eureka上注册自己
    fetch-registry: false # 是否拉取服务列表
  server:
    enable-self-preservation: false # 关闭自我保护模式
    eviction-interval-timer-in-ms: 10000 # 定期清理无效连接