## 端口号
server:
  port: 10010

spring:
  application:
    name: gateway

## 配置eureka
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka

## zuul 路由功能(配置路由)
zuul:
  prefix: /api
  routes:
    ## 自定义
    ## user-service: /user/**
    ## 默认配置
    ##consumer-service: /consumer-service/**
    ## 去前缀配置
    ##user-service: /user/**
    user-service:
      path: /user/**
      serviceId: user-service
      strip-prefix: false
  ## strip-prefix: true
  ignored-services:
    - consumer-service

## ribbon的超时时长,真实值是(read+connect)*2,必须小于hystrix时长
ribbon:
  ConnectTimeout: 500 # 连接超时时间(ms)
  ReadTimeout: 2000 # 通信超时时间(ms)
  MaxAutoRetriesNextServer: 0 # 同一服务不同实例的重试次数 0为不重试

## hystrix的熔断超时时长要比ribbon的超时时长
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMillisecond: 6000 # 熔断超时时长：6000ms


