## 端口号
server:
  port: 10086
## 项目名称
spring:
  application:
    name: lgl-eureka
## eureka客户端地址
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10088/eureka,http://127.0.0.1:10087/eureka
  server:
    eviction-interval-timer-in-ms: 10000 #失效剔除时间(剔除无效连接的间隔时间),单位ms(默认为60s)
    enable-self-preservation: false # 关闭自我保护机制(默认为true,打开)