## 端口号
server:
  port: 10010
## 服务名称
spring:
  application:
    name: ly-api-gateway
## eureka
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
## 网关的配置
zuul:
  prefix: /api # 添加路由前缀
  routes:
    ly-item-service: /item/**

## 降级熔断器
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMillisecond: 5000 # 熔断超时时长：5000ms

## 负载均衡配置
ribbon:
  ConnectTimeout: 1000 # 连接超时时间(ms)
  ReadTimeout: 3500 # 通信超时时间(ms)
  MaxAutoRetriesNextServer: 0 # 同一服务不同实例的重试次数
  MaxAutoRetries: 0 # 同一实例的重试次数
