## 端口号
server:
  port: 8081
## 服务名称
spring:
  application:
    name: item-service
  datasource: # 数据库信息
    url: jdbc:mysql://192.168.3.34:3306/leyou
    username: root
    password: Cy520==1314
    driver-class-name: com.mysql.jdbc.Driver
  rabbitmq: # RabbitMQ 配置
    host: 192.168.3.34 # IP地址
    virtual-host: /leyou # 虚拟路径
    username: leyou # 用户名
    password: leyou # 密码
    template: # 模板
      exchange: LEYOU.ITEM.EXCHANGE # 配置交换机
## eureka注册服务中心
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    lease-renewal-interval-in-seconds: 5 # 心跳时间
    lease-expiration-duration-in-seconds: 15 # 过期时间
mybatis:
  type-aliases-package: com.leyou.item.pojo # mybatis实体类路径