## 端口号
server:
  port: 8087
## 微服务名称
spring:
  application:
    name: auth-service
## eureka注册中心
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka # 注册地址
    registry-fetch-interval-seconds: 10 # 拉取服务时间
  instance:
    lease-renewal-interval-in-seconds: 5 # 心跳时间
    lease-expiration-duration-in-seconds: 15 # 过期时间
## jwt配置
leyou:
  jwt:
    secret: leyou@Login(Auth}*^31)&heiMa% # 登录校验的密钥
    pubKeyPath: /Users/liguoliang/Desktop/test/rsa.pub # 公钥地址
    priKeyPath: /Users/liguoliang/Desktop/test/rsa.pri # 私钥地址
    expire: 30 # 过期时间,单位分钟
    cookieName: LY_TOKEN